/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetadataFilter } from './MetadataFilter';
import {
    MetadataFilterFromJSON,
    MetadataFilterFromJSONTyped,
    MetadataFilterToJSON,
    MetadataFilterToJSONTyped,
} from './MetadataFilter';

/**
 * Request body for paginated document fetching.
 * @export
 * @interface DocumentFetchRequest
 */
export interface DocumentFetchRequest {
    /**
     * Number of documents per page (1 to 1000)
     * @type {number}
     * @memberof DocumentFetchRequest
     */
    page_size?: number;
    /**
     * Pagination token returned by a previous fetch call. Omit or set to null to start from the beginning.
     * @type {string}
     * @memberof DocumentFetchRequest
     */
    after?: string;
    /**
     * 
     * @type {MetadataFilter}
     * @memberof DocumentFetchRequest
     */
    metadata_filter?: MetadataFilter;
    /**
     * Optional filter to include only documents with specific tags (max 50 tags).
     * @type {Array<string>}
     * @memberof DocumentFetchRequest
     */
    document_tags?: Array<string>;
    /**
     * If True, documents must have ALL specified tags (AND). If False, ANY (OR).
     * @type {boolean}
     * @memberof DocumentFetchRequest
     */
    document_tags_match_all?: boolean;
}

/**
 * Check if a given object implements the DocumentFetchRequest interface.
 */
export function instanceOfDocumentFetchRequest(value: object): value is DocumentFetchRequest {
    return true;
}

export function DocumentFetchRequestFromJSON(json: any): DocumentFetchRequest {
    return DocumentFetchRequestFromJSONTyped(json, false);
}

export function DocumentFetchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentFetchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'page_size': json['page_size'] == null ? undefined : json['page_size'],
        'after': json['after'] == null ? undefined : json['after'],
        'metadata_filter': json['metadata_filter'] == null ? undefined : MetadataFilterFromJSON(json['metadata_filter']),
        'document_tags': json['document_tags'] == null ? undefined : json['document_tags'],
        'document_tags_match_all': json['document_tags_match_all'] == null ? undefined : json['document_tags_match_all'],
    };
}

export function DocumentFetchRequestToJSON(json: any): DocumentFetchRequest {
    return DocumentFetchRequestToJSONTyped(json, false);
}

export function DocumentFetchRequestToJSONTyped(value?: DocumentFetchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page_size': value['page_size'],
        'after': value['after'],
        'metadata_filter': MetadataFilterToJSON(value['metadata_filter']),
        'document_tags': value['document_tags'],
        'document_tags_match_all': value['document_tags_match_all'],
    };
}

