/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search Engine
 *
 * The version of the OpenAPI document: 1.0.0-beta3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomDocumentVector } from './CustomDocumentVector';
import {
    CustomDocumentVectorFromJSON,
    CustomDocumentVectorFromJSONTyped,
    CustomDocumentVectorToJSON,
    CustomDocumentVectorToJSONTyped,
} from './CustomDocumentVector';

/**
 * Document model representing the structure of documents in the system.
 * 
 * This model is used for document ingestion, retrieval, and search results.
 * Content is excluded from database storage for performance and cost reasons.
 * @export
 * @interface Document
 */
export interface Document {
    /**
     * Unique identifier for the document (max 100 characters)
     * @type {string}
     * @memberof Document
     */
    id: string;
    /**
     * UTC timestamp when the document was created/updated
     * @type {Date}
     * @memberof Document
     */
    timestamp: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof Document
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    content?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Document
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Array<CustomDocumentVector>}
     * @memberof Document
     */
    custom_vectors?: Array<CustomDocumentVector> | null;
}

/**
 * Check if a given object implements the Document interface.
 */
export function instanceOfDocument(value: object): value is Document {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function DocumentFromJSON(json: any): Document {
    return DocumentFromJSONTyped(json, false);
}

export function DocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Document {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': (new Date(json['timestamp'])),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'content': json['content'] == null ? undefined : json['content'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'custom_vectors': json['custom_vectors'] == null ? undefined : ((json['custom_vectors'] as Array<any>).map(CustomDocumentVectorFromJSON)),
    };
}

export function DocumentToJSON(json: any): Document {
    return DocumentToJSONTyped(json, false);
}

export function DocumentToJSONTyped(value?: Document | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'timestamp': value['timestamp'].toISOString(),
        'tags': value['tags'],
        'name': value['name'],
        'description': value['description'],
        'content': value['content'],
        'metadata': value['metadata'],
        'custom_vectors': value['custom_vectors'] == null ? undefined : ((value['custom_vectors'] as Array<any>).map(CustomDocumentVectorToJSON)),
    };
}

