/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search Engine
 *
 * The version of the OpenAPI document: 1.0.0-beta3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Individual status entry for a document.
 * @export
 * @interface DocumentStatus
 */
export interface DocumentStatus {
    /**
     * Status of the document (queued, requeued, indexed, failed)
     * @type {DocumentStatusStatusEnum}
     * @memberof DocumentStatus
     */
    status: DocumentStatusStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof DocumentStatus
     */
    info?: string | null;
    /**
     * When this status occurred
     * @type {Date}
     * @memberof DocumentStatus
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof DocumentStatus
     */
    queue_id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DocumentStatus
     */
    try_count?: number | null;
}


/**
 * @export
 */
export const DocumentStatusStatusEnum = {
    Queued: 'queued',
    Requeued: 'requeued',
    Indexed: 'indexed',
    Failed: 'failed'
} as const;
export type DocumentStatusStatusEnum = typeof DocumentStatusStatusEnum[keyof typeof DocumentStatusStatusEnum];


/**
 * Check if a given object implements the DocumentStatus interface.
 */
export function instanceOfDocumentStatus(value: object): value is DocumentStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function DocumentStatusFromJSON(json: any): DocumentStatus {
    return DocumentStatusFromJSONTyped(json, false);
}

export function DocumentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'info': json['info'] == null ? undefined : json['info'],
        'timestamp': (new Date(json['timestamp'])),
        'queue_id': json['queue_id'] == null ? undefined : json['queue_id'],
        'try_count': json['try_count'] == null ? undefined : json['try_count'],
    };
}

export function DocumentStatusToJSON(json: any): DocumentStatus {
    return DocumentStatusToJSONTyped(json, false);
}

export function DocumentStatusToJSONTyped(value?: DocumentStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'info': value['info'],
        'timestamp': value['timestamp'].toISOString(),
        'queue_id': value['queue_id'],
        'try_count': value['try_count'],
    };
}

