/* tslint:disable */
/* eslint-disable */
/**
 * Amgix API
 * Amgix (Amalgam Index) - Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Document } from './Document';
import {
    DocumentFromJSON,
    DocumentFromJSONTyped,
    DocumentToJSON,
    DocumentToJSONTyped,
} from './Document';

/**
 * Response for paginated document fetching.
 * @export
 * @interface DocumentFetchResponse
 */
export interface DocumentFetchResponse {
    /**
     * Page of documents
     * @type {Array<Document>}
     * @memberof DocumentFetchResponse
     */
    documents: Array<Document>;
    /**
     * Pagination token for the next page. Null when there are no more documents.
     * @type {string}
     * @memberof DocumentFetchResponse
     */
    after?: string;
}

/**
 * Check if a given object implements the DocumentFetchResponse interface.
 */
export function instanceOfDocumentFetchResponse(value: object): value is DocumentFetchResponse {
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function DocumentFetchResponseFromJSON(json: any): DocumentFetchResponse {
    return DocumentFetchResponseFromJSONTyped(json, false);
}

export function DocumentFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'documents': ((json['documents'] as Array<any>).map(DocumentFromJSON)),
        'after': json['after'] == null ? undefined : json['after'],
    };
}

export function DocumentFetchResponseToJSON(json: any): DocumentFetchResponse {
    return DocumentFetchResponseToJSONTyped(json, false);
}

export function DocumentFetchResponseToJSONTyped(value?: DocumentFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documents': ((value['documents'] as Array<any>).map(DocumentToJSON)),
        'after': value['after'],
    };
}

