/* tslint:disable */
/* eslint-disable */
/**
 * Amgix API
 * Amgix (Amalgam Index) - Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Tuning for faceting; used only when SearchQuery.facets is True.
 * @export
 * @interface FacetOptions
 */
export interface FacetOptions {
    /**
     * Multiplier on query.limit setting the per-arm candidate window for facet computation. The window is floored to at least 50 candidates. Larger multipliers yield more accurate distributions at higher cost (1 to 10).
     * @type {number}
     * @memberof FacetOptions
     */
    prefetch_multiplier?: number;
    /**
     * Maximum distinct values returned per facet field, kept as the top-N by count (1 to 100).
     * @type {number}
     * @memberof FacetOptions
     */
    max_values?: number;
}

/**
 * Check if a given object implements the FacetOptions interface.
 */
export function instanceOfFacetOptions(value: object): value is FacetOptions {
    return true;
}

export function FacetOptionsFromJSON(json: any): FacetOptions {
    return FacetOptionsFromJSONTyped(json, false);
}

export function FacetOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacetOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'prefetch_multiplier': json['prefetch_multiplier'] == null ? undefined : json['prefetch_multiplier'],
        'max_values': json['max_values'] == null ? undefined : json['max_values'],
    };
}

export function FacetOptionsToJSON(json: any): FacetOptions {
    return FacetOptionsToJSONTyped(json, false);
}

export function FacetOptionsToJSONTyped(value?: FacetOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prefetch_multiplier': value['prefetch_multiplier'],
        'max_values': value['max_values'],
    };
}

