/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional join of another collection onto each search result. Forms: '<collection>', '<collection>[<parent>=<child>]', or with '(<filter>)'. Parent refs: $id, $.meta.<key>. Child refs: $$id, $$.meta.<key>. Omitted '[]' defaults to [$id=$$id]. Joined documents appear under joined[collection_name].
 * @export
 * @interface Join1
 */
export interface Join1 {
}

/**
 * Check if a given object implements the Join1 interface.
 */
export function instanceOfJoin1(value: object): value is Join1 {
    return true;
}

export function Join1FromJSON(json: any): Join1 {
    return Join1FromJSONTyped(json, false);
}

export function Join1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Join1 {
    return json;
}

export function Join1ToJSON(json: any): Join1 {
    return Join1ToJSONTyped(json, false);
}

export function Join1ToJSONTyped(value?: Join1 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

