/* tslint:disable */
/* eslint-disable */
/**
 * Amgix API
 * Amgix (Amalgam Index) - Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional join of another collection onto each fetched document. Forms: '<collection>', '<collection>[<parent>=<child>]', or with '(<filter>)'. Parent refs: $id, $.meta.<key>. Child refs: $$id, $$.meta.<key>. Omitted '[]' defaults to [$id=$$id]. Joined documents appear under joined[collection_name].
 * @export
 * @interface Join
 */
export interface Join {
}

/**
 * Check if a given object implements the Join interface.
 */
export function instanceOfJoin(value: object): value is Join {
    return true;
}

export function JoinFromJSON(json: any): Join {
    return JoinFromJSONTyped(json, false);
}

export function JoinFromJSONTyped(json: any, ignoreDiscriminator: boolean): Join {
    return json;
}

export function JoinToJSON(json: any): Join {
    return JoinToJSONTyped(json, false);
}

export function JoinToJSONTyped(value?: Join | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

