/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetadataFilter } from './MetadataFilter';
import {
    MetadataFilterFromJSON,
    MetadataFilterFromJSONTyped,
    MetadataFilterToJSON,
    MetadataFilterToJSONTyped,
} from './MetadataFilter';

/**
 * Optional metadata filter. Accepts either a MetadataFilter object or a filter expression string (e.g. 'year > 2020 AND status = "active"'). Only fields declared in collection metadata_indexes can be filtered.
 * @export
 * @interface MetadataFilter1
 */
export interface MetadataFilter1 {
    /**
     * All conditions in this list must match (AND)
     * @type {Array<MetadataFilter>}
     * @memberof MetadataFilter1
     */
    and?: Array<MetadataFilter>;
    /**
     * Any condition in this list must match (OR)
     * @type {Array<MetadataFilter>}
     * @memberof MetadataFilter1
     */
    or?: Array<MetadataFilter>;
    /**
     * This condition must NOT match (NOT)
     * @type {MetadataFilter}
     * @memberof MetadataFilter1
     */
    not?: MetadataFilter;
    /**
     * Metadata field key (for field condition)
     * @type {string}
     * @memberof MetadataFilter1
     */
    key?: string;
    /**
     * Comparison operator
     * @type {MetadataFilter1OpEnum}
     * @memberof MetadataFilter1
     */
    op?: MetadataFilter1OpEnum;
    /**
     * 
     * @type {any}
     * @memberof MetadataFilter1
     */
    value?: any | null;
}


/**
 * @export
 */
export const MetadataFilter1OpEnum = {
    Eq: 'eq',
    Neq: 'neq',
    Lt: 'lt',
    Gt: 'gt',
    Lte: 'lte',
    Gte: 'gte'
} as const;
export type MetadataFilter1OpEnum = typeof MetadataFilter1OpEnum[keyof typeof MetadataFilter1OpEnum];


/**
 * Check if a given object implements the MetadataFilter1 interface.
 */
export function instanceOfMetadataFilter1(value: object): value is MetadataFilter1 {
    return true;
}

export function MetadataFilter1FromJSON(json: any): MetadataFilter1 {
    return MetadataFilter1FromJSONTyped(json, false);
}

export function MetadataFilter1FromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataFilter1 {
    if (json == null) {
        return json;
    }
    return {
        
        'and': json['and'] == null ? undefined : ((json['and'] as Array<any>).map(MetadataFilterFromJSON)),
        'or': json['or'] == null ? undefined : ((json['or'] as Array<any>).map(MetadataFilterFromJSON)),
        'not': json['not'] == null ? undefined : MetadataFilterFromJSON(json['not']),
        'key': json['key'] == null ? undefined : json['key'],
        'op': json['op'] == null ? undefined : json['op'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function MetadataFilter1ToJSON(json: any): MetadataFilter1 {
    return MetadataFilter1ToJSONTyped(json, false);
}

export function MetadataFilter1ToJSONTyped(value?: MetadataFilter1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'and': value['and'] == null ? undefined : ((value['and'] as Array<any>).map(MetadataFilterToJSON)),
        'or': value['or'] == null ? undefined : ((value['or'] as Array<any>).map(MetadataFilterToJSON)),
        'not': MetadataFilterToJSON(value['not']),
        'key': value['key'],
        'op': value['op'],
        'value': value['value'],
    };
}

