/* tslint:disable */
/* eslint-disable */
/**
 * Amgix API
 * Amgix (Amalgam Index) - Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchResult } from './SearchResult';
import {
    SearchResultFromJSON,
    SearchResultFromJSONTyped,
    SearchResultToJSON,
    SearchResultToJSONTyped,
} from './SearchResult';

/**
 * Response from a search query.
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
    /**
     * Search hits, ordered by relevance
     * @type {Array<SearchResult>}
     * @memberof SearchResponse
     */
    results: Array<SearchResult>;
    /**
     * Per-facet-field value counts over the search candidate pool. Only present when facets was True in the request. Keys are metadata field names; inner keys are stringified facet values; inner values are candidate counts.
     * @type {{ [key: string]: { [key: string]: number; }; }}
     * @memberof SearchResponse
     */
    facet_counts?: { [key: string]: { [key: string]: number; }; };
    /**
     * Server-side time to execute this search, in milliseconds
     * @type {number}
     * @memberof SearchResponse
     */
    query_time_ms: number;
}

/**
 * Check if a given object implements the SearchResponse interface.
 */
export function instanceOfSearchResponse(value: object): value is SearchResponse {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('query_time_ms' in value) || value['query_time_ms'] === undefined) return false;
    return true;
}

export function SearchResponseFromJSON(json: any): SearchResponse {
    return SearchResponseFromJSONTyped(json, false);
}

export function SearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(SearchResultFromJSON)),
        'facet_counts': json['facet_counts'] == null ? undefined : json['facet_counts'],
        'query_time_ms': json['query_time_ms'],
    };
}

export function SearchResponseToJSON(json: any): SearchResponse {
    return SearchResponseToJSONTyped(json, false);
}

export function SearchResponseToJSONTyped(value?: SearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(SearchResultToJSON)),
        'facet_counts': value['facet_counts'],
        'query_time_ms': value['query_time_ms'],
    };
}

