/* tslint:disable */
/* eslint-disable */
/**
 * Amgix API
 * Amgix (Amalgam Index) - Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Join1 } from './Join1';
import {
    Join1FromJSON,
    Join1FromJSONTyped,
    Join1ToJSON,
    Join1ToJSONTyped,
} from './Join1';
import type { CustomVector } from './CustomVector';
import {
    CustomVectorFromJSON,
    CustomVectorFromJSONTyped,
    CustomVectorToJSON,
    CustomVectorToJSONTyped,
} from './CustomVector';
import type { VectorSearchOption } from './VectorSearchOption';
import {
    VectorSearchOptionFromJSON,
    VectorSearchOptionFromJSONTyped,
    VectorSearchOptionToJSON,
    VectorSearchOptionToJSONTyped,
} from './VectorSearchOption';
import type { FacetOptions } from './FacetOptions';
import {
    FacetOptionsFromJSON,
    FacetOptionsFromJSONTyped,
    FacetOptionsToJSON,
    FacetOptionsToJSONTyped,
} from './FacetOptions';
import type { MetadataFilter1 } from './MetadataFilter1';
import {
    MetadataFilter1FromJSON,
    MetadataFilter1FromJSONTyped,
    MetadataFilter1ToJSON,
    MetadataFilter1ToJSONTyped,
} from './MetadataFilter1';

/**
 * Configuration for a search query.
 * Defines the query string and vector options.
 * This is the model that will be sent by end users to the search API endpoint.
 * @export
 * @interface SearchQuery
 */
export interface SearchQuery {
    /**
     * The search query string (max 10000 characters)
     * @type {string}
     * @memberof SearchQuery
     */
    query: string;
    /**
     * List of vectors, fields, and weights to use for searching. If empty, equal weights will be auto-generated for all available vectors.
     * @type {Array<VectorSearchOption>}
     * @memberof SearchQuery
     */
    vector_options?: Array<VectorSearchOption>;
    /**
     * Pre-generated custom vectors for this search query (optional)
     * @type {Array<CustomVector>}
     * @memberof SearchQuery
     */
    custom_vectors?: Array<CustomVector>;
    /**
     * Maximum number of results to return (1 to 100)
     * @type {number}
     * @memberof SearchQuery
     */
    limit?: number;
    /**
     * Optional minimum score threshold. Results below this score will be excluded
     * @type {number}
     * @memberof SearchQuery
     */
    score_threshold?: number;
    /**
     * Optional filter to include only documents with specific tags (max 50 tags, each max 100 characters; cannot contain pipe characters)
     * @type {Array<string>}
     * @memberof SearchQuery
     */
    document_tags?: Array<string>;
    /**
     * If True, documents must have ALL specified tags (AND). If False, documents must have ANY of the specified tags (OR).
     * @type {boolean}
     * @memberof SearchQuery
     */
    document_tags_match_all?: boolean;
    /**
     * 
     * @type {MetadataFilter1}
     * @memberof SearchQuery
     */
    metadata_filter?: MetadataFilter1;
    /**
     * 
     * @type {Join1}
     * @memberof SearchQuery
     */
    join?: Join1;
    /**
     * Optional list of document fields to omit from search results (and from documents attached via 'joined'). Allowed values: name, description, content, tags, metadata.
     * @type {Array<SearchQueryExcludeEnum>}
     * @memberof SearchQuery
     */
    exclude?: Array<SearchQueryExcludeEnum>;
    /**
     * Optional indexed metadata field to group results by. When set, results are capped at group_max per distinct value of this field, refetching up to group_max_fetches times if needed to fill the requested limit.
     * @type {string}
     * @memberof SearchQuery
     */
    group_field?: string;
    /**
     * Maximum number of results allowed per group_field value
     * @type {number}
     * @memberof SearchQuery
     */
    group_max?: number;
    /**
     * Total number of fetches (including the first) allowed while grouping
     * @type {number}
     * @memberof SearchQuery
     */
    group_max_fetches?: number;
    /**
     * If True, compute facet counts over the candidate pool for every field declared in the collection's metadata_indexes. Counts are returned in SearchResponse.facet_counts.
     * @type {boolean}
     * @memberof SearchQuery
     */
    facets?: boolean;
    /**
     * Tuning for faceting (prefetch window and max values per field). Used only when facets is True.
     * @type {FacetOptions}
     * @memberof SearchQuery
     */
    facet_options?: FacetOptions;
    /**
     * Whether to include individual vector scores in results
     * @type {boolean}
     * @memberof SearchQuery
     */
    raw_scores?: boolean;
    /**
     * How to combine multi-vector search results. 'rrf' = reciprocal rank fusion (rank-based). 'linear' = min-max normalize each retriever's scores on its prefetch list, then sum weight * normalized score.
     * @type {SearchQueryFusionModeEnum}
     * @memberof SearchQuery
     */
    fusion_mode?: SearchQueryFusionModeEnum;
}


/**
 * @export
 */
export const SearchQueryExcludeEnum = {
    Name: 'name',
    Description: 'description',
    Content: 'content',
    Tags: 'tags',
    Metadata: 'metadata'
} as const;
export type SearchQueryExcludeEnum = typeof SearchQueryExcludeEnum[keyof typeof SearchQueryExcludeEnum];

/**
 * @export
 */
export const SearchQueryFusionModeEnum = {
    Rrf: 'rrf',
    Linear: 'linear'
} as const;
export type SearchQueryFusionModeEnum = typeof SearchQueryFusionModeEnum[keyof typeof SearchQueryFusionModeEnum];


/**
 * Check if a given object implements the SearchQuery interface.
 */
export function instanceOfSearchQuery(value: object): value is SearchQuery {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function SearchQueryFromJSON(json: any): SearchQuery {
    return SearchQueryFromJSONTyped(json, false);
}

export function SearchQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'vector_options': json['vector_options'] == null ? undefined : ((json['vector_options'] as Array<any>).map(VectorSearchOptionFromJSON)),
        'custom_vectors': json['custom_vectors'] == null ? undefined : ((json['custom_vectors'] as Array<any>).map(CustomVectorFromJSON)),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'score_threshold': json['score_threshold'] == null ? undefined : json['score_threshold'],
        'document_tags': json['document_tags'] == null ? undefined : json['document_tags'],
        'document_tags_match_all': json['document_tags_match_all'] == null ? undefined : json['document_tags_match_all'],
        'metadata_filter': json['metadata_filter'] == null ? undefined : MetadataFilter1FromJSON(json['metadata_filter']),
        'join': json['join'] == null ? undefined : Join1FromJSON(json['join']),
        'exclude': json['exclude'] == null ? undefined : json['exclude'],
        'group_field': json['group_field'] == null ? undefined : json['group_field'],
        'group_max': json['group_max'] == null ? undefined : json['group_max'],
        'group_max_fetches': json['group_max_fetches'] == null ? undefined : json['group_max_fetches'],
        'facets': json['facets'] == null ? undefined : json['facets'],
        'facet_options': json['facet_options'] == null ? undefined : FacetOptionsFromJSON(json['facet_options']),
        'raw_scores': json['raw_scores'] == null ? undefined : json['raw_scores'],
        'fusion_mode': json['fusion_mode'] == null ? undefined : json['fusion_mode'],
    };
}

export function SearchQueryToJSON(json: any): SearchQuery {
    return SearchQueryToJSONTyped(json, false);
}

export function SearchQueryToJSONTyped(value?: SearchQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'vector_options': value['vector_options'] == null ? undefined : ((value['vector_options'] as Array<any>).map(VectorSearchOptionToJSON)),
        'custom_vectors': value['custom_vectors'] == null ? undefined : ((value['custom_vectors'] as Array<any>).map(CustomVectorToJSON)),
        'limit': value['limit'],
        'score_threshold': value['score_threshold'],
        'document_tags': value['document_tags'],
        'document_tags_match_all': value['document_tags_match_all'],
        'metadata_filter': MetadataFilter1ToJSON(value['metadata_filter']),
        'join': Join1ToJSON(value['join']),
        'exclude': value['exclude'],
        'group_field': value['group_field'],
        'group_max': value['group_max'],
        'group_max_fetches': value['group_max_fetches'],
        'facets': value['facets'],
        'facet_options': FacetOptionsToJSON(value['facet_options']),
        'raw_scores': value['raw_scores'],
        'fusion_mode': value['fusion_mode'],
    };
}

