/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search Engine
 *
 * The version of the OpenAPI document: 1.0.0-beta3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VectorScore } from './VectorScore';
import {
    VectorScoreFromJSON,
    VectorScoreFromJSONTyped,
    VectorScoreToJSON,
    VectorScoreToJSONTyped,
} from './VectorScore';
import type { CustomDocumentVector } from './CustomDocumentVector';
import {
    CustomDocumentVectorFromJSON,
    CustomDocumentVectorFromJSONTyped,
    CustomDocumentVectorToJSON,
    CustomDocumentVectorToJSONTyped,
} from './CustomDocumentVector';

/**
 * A search result containing document information and its relevance score.
 * Inherits from Document but excludes content field and adds score.
 * 
 * Validation is disabled for SearchResult as it is constructed internally from validated data.
 * @export
 * @interface SearchResult
 */
export interface SearchResult {
    /**
     * Unique identifier for the document (max 100 characters)
     * @type {string}
     * @memberof SearchResult
     */
    id: string;
    /**
     * UTC timestamp when the document was created/updated
     * @type {Date}
     * @memberof SearchResult
     */
    timestamp: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchResult
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    description?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SearchResult
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Array<CustomDocumentVector>}
     * @memberof SearchResult
     */
    custom_vectors?: Array<CustomDocumentVector> | null;
    /**
     * The relevance score for this document
     * @type {number}
     * @memberof SearchResult
     */
    score: number;
    /**
     * Raw per-vector scores with field, vector, score, and rank information
     * @type {Array<VectorScore>}
     * @memberof SearchResult
     */
    vector_scores?: Array<VectorScore>;
}

/**
 * Check if a given object implements the SearchResult interface.
 */
export function instanceOfSearchResult(value: object): value is SearchResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function SearchResultFromJSON(json: any): SearchResult {
    return SearchResultFromJSONTyped(json, false);
}

export function SearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': (new Date(json['timestamp'])),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'custom_vectors': json['custom_vectors'] == null ? undefined : ((json['custom_vectors'] as Array<any>).map(CustomDocumentVectorFromJSON)),
        'score': json['score'],
        'vector_scores': json['vector_scores'] == null ? undefined : ((json['vector_scores'] as Array<any>).map(VectorScoreFromJSON)),
    };
}

export function SearchResultToJSON(json: any): SearchResult {
    return SearchResultToJSONTyped(json, false);
}

export function SearchResultToJSONTyped(value?: SearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'timestamp': value['timestamp'].toISOString(),
        'tags': value['tags'],
        'name': value['name'],
        'description': value['description'],
        'metadata': value['metadata'],
        'custom_vectors': value['custom_vectors'] == null ? undefined : ((value['custom_vectors'] as Array<any>).map(CustomDocumentVectorToJSON)),
        'score': value['score'],
        'vector_scores': value['vector_scores'] == null ? undefined : ((value['vector_scores'] as Array<any>).map(VectorScoreToJSON)),
    };
}

