/* tslint:disable */
/* eslint-disable */
/**
 * Amgix API
 * Amgix (Amalgam Index) - Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Vector data for a specific vector.
 * Contains the precalculated vector values, which can be either dense or sparse.
 * @export
 * @interface VectorData
 */
export interface VectorData {
    /**
     * Name of the vector
     * @type {string}
     * @memberof VectorData
     */
    vector_name: string;
    /**
     * Field this vector is for (name, description, content)
     * @type {VectorDataFieldEnum}
     * @memberof VectorData
     */
    field: VectorDataFieldEnum;
    /**
     * Type of vector (dense_model, sparse_model, full_text, trigrams, whitespace, wmtr, dense_custom, sparse_custom)
     * @type {VectorDataVectorTypeEnum}
     * @memberof VectorData
     */
    vector_type: VectorDataVectorTypeEnum;
    /**
     * Dense vector values as a list of floats
     * @type {Array<number>}
     * @memberof VectorData
     */
    dense_vector?: Array<number>;
    /**
     * Sparse vector indices (token positions)
     * @type {Array<number>}
     * @memberof VectorData
     */
    sparse_indices?: Array<number>;
    /**
     * Sparse vector values (token weights)
     * @type {Array<number>}
     * @memberof VectorData
     */
    sparse_values?: Array<number>;
}


/**
 * @export
 */
export const VectorDataFieldEnum = {
    Name: 'name',
    Description: 'description',
    Content: 'content'
} as const;
export type VectorDataFieldEnum = typeof VectorDataFieldEnum[keyof typeof VectorDataFieldEnum];

/**
 * @export
 */
export const VectorDataVectorTypeEnum = {
    DenseModel: 'dense_model',
    SparseModel: 'sparse_model',
    FullText: 'full_text',
    Trigrams: 'trigrams',
    Whitespace: 'whitespace',
    Wmtr: 'wmtr',
    Keyword: 'keyword',
    DenseCustom: 'dense_custom',
    SparseCustom: 'sparse_custom',
    Noop: 'noop'
} as const;
export type VectorDataVectorTypeEnum = typeof VectorDataVectorTypeEnum[keyof typeof VectorDataVectorTypeEnum];


/**
 * Check if a given object implements the VectorData interface.
 */
export function instanceOfVectorData(value: object): value is VectorData {
    if (!('vector_name' in value) || value['vector_name'] === undefined) return false;
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('vector_type' in value) || value['vector_type'] === undefined) return false;
    return true;
}

export function VectorDataFromJSON(json: any): VectorData {
    return VectorDataFromJSONTyped(json, false);
}

export function VectorDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorData {
    if (json == null) {
        return json;
    }
    return {
        
        'vector_name': json['vector_name'],
        'field': json['field'],
        'vector_type': json['vector_type'],
        'dense_vector': json['dense_vector'] == null ? undefined : json['dense_vector'],
        'sparse_indices': json['sparse_indices'] == null ? undefined : json['sparse_indices'],
        'sparse_values': json['sparse_values'] == null ? undefined : json['sparse_values'],
    };
}

export function VectorDataToJSON(json: any): VectorData {
    return VectorDataToJSONTyped(json, false);
}

export function VectorDataToJSONTyped(value?: VectorData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vector_name': value['vector_name'],
        'field': value['field'],
        'vector_type': value['vector_type'],
        'dense_vector': value['dense_vector'],
        'sparse_indices': value['sparse_indices'],
        'sparse_values': value['sparse_values'],
    };
}

