/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). The Hybrid Semantic Search Platform, API
 *
 * The version of the OpenAPI document: 1.0.0-beta3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Configuration for a vector search weight.
 * Used in search queries to specify which vectors to search with and their weights.
 * @export
 * @interface VectorSearchWeight
 */
export interface VectorSearchWeight {
    [key: string]: any | any;
    /**
     * Name of the vector to search with
     * @type {string}
     * @memberof VectorSearchWeight
     */
    vector_name: string;
    /**
     * Weight to apply to this vector's search results
     * @type {number}
     * @memberof VectorSearchWeight
     */
    weight?: number;
    /**
     * Field to search with this vector (name, description, content)
     * @type {string}
     * @memberof VectorSearchWeight
     */
    field: VectorSearchWeightFieldEnum;
}


/**
 * @export
 */
export const VectorSearchWeightFieldEnum = {
    Name: 'name',
    Description: 'description',
    Content: 'content'
} as const;
export type VectorSearchWeightFieldEnum = typeof VectorSearchWeightFieldEnum[keyof typeof VectorSearchWeightFieldEnum];


/**
 * Check if a given object implements the VectorSearchWeight interface.
 */
export function instanceOfVectorSearchWeight(value: object): value is VectorSearchWeight {
    if (!('vector_name' in value) || value['vector_name'] === undefined) return false;
    if (!('field' in value) || value['field'] === undefined) return false;
    return true;
}

export function VectorSearchWeightFromJSON(json: any): VectorSearchWeight {
    return VectorSearchWeightFromJSONTyped(json, false);
}

export function VectorSearchWeightFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorSearchWeight {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'vector_name': json['vector_name'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'field': json['field'],
    };
}

export function VectorSearchWeightToJSON(json: any): VectorSearchWeight {
    return VectorSearchWeightToJSONTyped(json, false);
}

export function VectorSearchWeightToJSONTyped(value?: VectorSearchWeight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'vector_name': value['vector_name'],
        'weight': value['weight'],
        'field': value['field'],
    };
}

